/*
 * Checks levels.js on its own.
 *
 * It reads the file from disk, looks only at the letters in the maps, and
 * tests every rule again. It has its own copy of the solver, so it does not
 * trust anything the maker said. It prints one line for each level and stops
 * with an error code if any line says FAIL.
 *
 * Run it with:  node tools\checklevels.cjs
 */

'use strict';

const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'levels.js');

// ---------------------------------------------------------------------------
// what the game says
// ---------------------------------------------------------------------------

const RUN_H = 17;
const ROOM_W = 15;
const ROOM_H = 17;
const RUN_FLOOR = 14;

const MAXDX_UP = [4, 3, 3, 2];
const MAXDX_WALL = [0, 3, 3, 2];
const SPRING_RISE = 6;
const SPRING_DX = 2;
const SOLID_SET = '#=T/';

const WORLD_NAMES = [
  'Green Woods', 'Frost Peak', 'Sand Tomb', 'Fire Keep',
  'Shadow Fort', 'Sky Temple', 'Deep Cave', 'Iron Works'
];
const ENEMIES = [
  ['Z', 'S'], ['W', 'V'], ['U', 'C'], ['I', 'G'],
  ['N', 'Y'], ['A', 'E'], ['L', 'O'], ['f', 'j']
];
const BOSSES = ['K', 'J', 'Q', 'D', 'X', '7', '8', '9'];
const ALL_ENEMY_CH = 'ZSWVUCIGNYAELOfj';
const ALL_BOSS_CH = 'KJQDX789';
const LEGAL = '.#=^~T%+|/PFoHM*BRkg123456' + ALL_ENEMY_CH + ALL_BOSS_CH;
const LAVA_WORLDS = [3, 6];

// ---------------------------------------------------------------------------
// read the file
// ---------------------------------------------------------------------------

const src = fs.readFileSync(FILE, 'utf8');
if (src.indexOf('/* Generated by tools/genlevels.cjs - do not edit by hand. */') !== 0) {
  console.error('levels.js does not start with the right header line');
  process.exit(1);
}
let LEVELS;
try {
  LEVELS = new Function(src + '\nreturn LEVELS;')();
} catch (err) {
  console.error('levels.js will not parse: ' + err.message);
  process.exit(1);
}
if (!Array.isArray(LEVELS)) {
  console.error('LEVELS is not a list');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// small helpers
// ---------------------------------------------------------------------------

function toGrid(rows) { return rows.map(function (r) { return r.split(''); }); }
function findAll(g, set) {
  const out = [];
  for (let y = 0; y < g.length; y++) {
    for (let x = 0; x < g[y].length; x++) {
      if (set.indexOf(g[y][x]) >= 0) out.push({ x: x, y: y, ch: g[y][x] });
    }
  }
  return out;
}
function groupCount(grid, ch) {
  const H = grid.length, W = grid[0].length;
  const seen = {};
  let n = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (grid[y][x] !== ch || seen[y + ':' + x]) continue;
      n++;
      const st = [[x, y]];
      while (st.length) {
        const p = st.pop();
        const k = p[1] + ':' + p[0];
        if (seen[k]) continue;
        seen[k] = true;
        [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(function (d) {
          const xx = p[0] + d[0], yy = p[1] + d[1];
          if (xx < 0 || yy < 0 || xx >= W || yy >= H) return;
          if (grid[yy][xx] === ch && !seen[yy + ':' + xx]) st.push([xx, yy]);
        });
      }
    }
  }
  return n;
}

// ---------------------------------------------------------------------------
// the solver, written again here on purpose
// ---------------------------------------------------------------------------

function makeSolver(rows) {
  const H = rows.length;
  const W = rows[0].length;

  function at(x, y) {
    if (x < 0 || y < 0 || x >= W || y >= H) return '#';
    return rows[y][x];
  }
  function solidCh(c, key) {
    return c === '#' || c === '=' || c === 'T' || c === '/' || (c === '+' && !key);
  }
  function solid(x, y, key) { return solidCh(at(x, y), key); }
  function free(x, y, key) {
    if (x < 0 || y < 0 || x >= W || y >= H) return false;
    const c = rows[y][x];
    return !solidCh(c, key) && c !== '^' && c !== '~';
  }
  function ladder(x, y) { return at(x, y) === '|'; }
  function rest(x, y, key) {
    return free(x, y, key) && (solid(x, y + 1, key) || ladder(x, y));
  }
  function cling(x, y, key) {
    if (!free(x, y, key)) return false;
    if (solid(x, y + 1, key) || ladder(x, y)) return false;
    return solid(x - 1, y, key) || solid(x + 1, y, key);
  }
  function pathOk(x, y, nx, ny, key, R) {
    const top = y - R;
    if (top < 0) return false;
    for (let r = y - 1; r >= top; r--) if (!free(x, r, key)) return false;
    const lo = Math.min(x, nx), hi = Math.max(x, nx);
    const midLow = Math.min(y - 1, ny);
    for (let mx = lo + 1; mx < hi; mx++) {
      for (let r = top; r <= midLow; r++) if (!free(mx, r, key)) return false;
    }
    for (let r = top; r <= ny; r++) if (!free(nx, r, key)) return false;
    return true;
  }
  function landing(x, y, key, nx, ny, R, push) {
    if (!pathOk(x, y, nx, ny, key, R)) return;
    if (rest(nx, ny, key)) push(nx, ny, 0);
    else if (cling(nx, ny, key)) push(nx, ny, 1);
  }
  function moves(x, y, mode, key, push) {
    if (mode === 0) {
      if (rest(x - 1, y, key)) push(x - 1, y, 0);
      if (rest(x + 1, y, key)) push(x + 1, y, 0);
      if (ladder(x, y - 1) && free(x, y - 1, key)) push(x, y - 1, 0);
      if (ladder(x, y) && ladder(x, y + 1)) push(x, y + 1, 0);
      for (let u = 0; u <= 3; u++) {
        const m = MAXDX_UP[u];
        for (let dx = -m; dx <= m; dx++) {
          if (dx === 0 && u === 0) continue;
          const R = Math.max(u + 1, Math.abs(dx), 1);
          landing(x, y, key, x + dx, y - u, R, push);
        }
      }
      for (let d = -1; d <= 1; d += 2) {
        for (let k = 1; k <= 4; k++) {
          const nx = x + d * k;
          if (k > 1 && !free(x + d * (k - 1), y, key)) break;
          for (let ny = y + 1; ny < H; ny++) {
            if (!free(nx, ny, key)) break;
            if (rest(nx, ny, key) || cling(nx, ny, key)) {
              landing(x, y, key, nx, ny, Math.max(k, 1), push);
            }
          }
        }
      }
      if (at(x, y + 1) === 'T') {
        for (let u = 1; u <= SPRING_RISE; u++) {
          for (let dx = -SPRING_DX; dx <= SPRING_DX; dx++) {
            const R = Math.max(u + 1, Math.abs(dx), 1);
            landing(x, y, key, x + dx, y - u, R, push);
          }
        }
      }
      return;
    }
    const wallLeft = solid(x - 1, y, key);
    const wallRight = solid(x + 1, y, key);
    for (let rise = 1; rise <= 3; rise++) {
      const m = MAXDX_WALL[rise];
      for (let d = -1; d <= 1; d += 2) {
        if (d < 0 && !wallRight) continue;
        if (d > 0 && !wallLeft) continue;
        for (let k = 1; k <= m; k++) {
          landing(x, y, key, x + d * k, y - rise, Math.max(rise + 1, k), push);
        }
      }
    }
    for (let d = -1; d <= 1; d++) {
      for (let ny = y + 1; ny < H; ny++) {
        const nx = x + d;
        if (!free(nx, ny, key)) break;
        if (rest(nx, ny, key) || cling(nx, ny, key)) landing(x, y, key, nx, ny, 1, push);
      }
    }
  }
  return { W: W, H: H, at: at, moves: moves };
}

function analyse(rows, opts) {
  opts = opts || {};
  const s = makeSolver(rows);
  const W = s.W, H = s.H;
  const grid = toGrid(rows);
  const start = findAll(grid, 'P')[0];
  const flag = findAll(grid, 'F')[0];
  if (!start || !flag) return null;

  const allowKey = opts.allowKey !== false;
  const N = W * H * 4;
  const dist = new Int32Array(N).fill(-1);
  const from = [];
  const to = [];
  function id(x, y, mode, key) { return ((y * W + x) * 2 + mode) * 2 + (key ? 1 : 0); }

  const s0 = id(start.x, start.y, 0, allowKey && s.at(start.x, start.y) === 'k');
  dist[s0] = 0;
  const queue = [s0];
  let head = 0;
  while (head < queue.length) {
    const cur = queue[head++];
    const key = (cur & 1) === 1;
    const mode = (cur >> 1) & 1;
    const cell = cur >> 2;
    const x = cell % W;
    const y = (cell - x) / W;
    const d = dist[cur];
    s.moves(x, y, mode, key, function (nx, ny, nmode) {
      let nkey = key;
      if (allowKey && s.at(nx, ny) === 'k') nkey = true;
      const nid = id(nx, ny, nmode, nkey);
      from.push(cur); to.push(nid);
      if (dist[nid] < 0) { dist[nid] = d + 1; queue.push(nid); }
    });
  }

  const back = new Int32Array(N).fill(-1);
  const heads = new Int32Array(N).fill(-1);
  const nextEdge = new Int32Array(from.length).fill(-1);
  for (let i = 0; i < from.length; i++) { nextEdge[i] = heads[to[i]]; heads[to[i]] = i; }
  const goals = [];
  for (let mode = 0; mode < 2; mode++) {
    for (let key = 0; key < 2; key++) {
      const gid = id(flag.x, flag.y, mode, key);
      if (dist[gid] >= 0) { back[gid] = 0; goals.push(gid); }
    }
  }
  const q2 = goals.slice();
  head = 0;
  while (head < q2.length) {
    const cur = q2[head++];
    for (let e = heads[cur]; e >= 0; e = nextEdge[e]) {
      const srcId = from[e];
      if (back[srcId] < 0) { back[srcId] = back[cur] + 1; q2.push(srcId); }
    }
  }
  let goalDist = -1;
  goals.forEach(function (g) { if (goalDist < 0 || dist[g] < goalDist) goalDist = dist[g]; });

  function best(arr, x, y) {
    let v = -1;
    for (let mode = 0; mode < 2; mode++) {
      for (let key = 0; key < 2; key++) {
        const t = arr[id(x, y, mode, key)];
        if (t >= 0 && (v < 0 || t < v)) v = t;
      }
    }
    return v;
  }
  return {
    ok: goalDist >= 0,
    reachable: function (x, y) { return best(dist, x, y) >= 0; },
    /* Spots you can get to but can never get out of. A player who lands
       in one is stuck for good, which is no fun at all. */
    traps: function () {
      const out = [];
      for (let y = 0; y < H; y++) {
        for (let x = 0; x < W; x++) {
          if (best(dist, x, y) >= 0 && best(back, x, y) < 0) { out.push(x + ',' + y); }
        }
      }
      return out;
    },
    detour: function (x, y) {
      const a = best(dist, x, y), b = best(back, x, y);
      if (a < 0 || b < 0) return false;
      return a + b > goalDist;
    }
  };
}

// ---------------------------------------------------------------------------
// how many things are there to do
// ---------------------------------------------------------------------------

function countFeatures(rows) {
  const H = rows.length, W = rows[0].length;
  let n = 0;
  const seen = {};
  function at(x, y) { return (x < 0 || y < 0 || x >= W || y >= H) ? '#' : rows[y][x]; }
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (at(x, y) !== 'o' || seen[y + ':' + x]) continue;
      n++;
      const stack = [[x, y]];
      while (stack.length) {
        const p = stack.pop();
        const k = p[1] + ':' + p[0];
        if (seen[k]) continue;
        seen[k] = true;
        [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(function (d) {
          const xx = p[0] + d[0], yy = p[1] + d[1];
          if (at(xx, yy) === 'o' && !seen[yy + ':' + xx]) stack.push([xx, yy]);
        });
      }
    }
  }
  '=^~/%|'.split('').forEach(function (ch) {
    for (let y = 0; y < H; y++) {
      let run = false;
      for (let x = 0; x < W; x++) {
        const on = at(x, y) === ch;
        if (on && !run) n++;
        run = on;
      }
    }
  });
  let inGap = false, lastTop = null;
  for (let x = 0; x < W; x++) {
    let top = null;
    for (let y = 0; y < H; y++) if (SOLID_SET.indexOf(at(x, y)) >= 0) { top = y; break; }
    const gap = top === null;
    if (gap && !inGap) n++;
    inGap = gap;
    if (top !== null && lastTop !== null && top !== lastTop) n++;
    if (top !== null) lastTop = top;
  }
  n += findAll(toGrid(rows), ALL_ENEMY_CH + ALL_BOSS_CH + 'THM*BRkg123456+').length;
  return n;
}

// ---------------------------------------------------------------------------
// rooms
// ---------------------------------------------------------------------------

function roomOf(x, y) { return Math.floor(x / ROOM_W) + ',' + Math.floor(y / ROOM_H); }
function roomBounds(C, R, W, H, c, r) {
  const wallCol = c < C - 1 ? (c + 1) * ROOM_W : W - 1;
  const floor = r < R - 1 ? (r + 1) * ROOM_H : H - 1;
  return {
    x0: c * ROOM_W + 1, x1: wallCol - 1,
    y0: r * ROOM_H + 1, y1: floor - 1,
    wallCol: wallCol, floor: floor, sr: floor - 1
  };
}
function roomGraph(rows, C, R) {
  const W = rows[0].length, H = rows.length;
  const nodes = [], adj = {};
  for (let r = 0; r < R; r++) {
    for (let c = 0; c < C; c++) { nodes.push(c + ',' + r); adj[c + ',' + r] = []; }
  }
  function open(ch) { return SOLID_SET.indexOf(ch) < 0; }
  for (let r = 0; r < R; r++) {
    for (let c = 0; c < C; c++) {
      const b = roomBounds(C, R, W, H, c, r);
      if (c + 1 < C) {
        let joined = false;
        for (let y = b.y0; y <= b.y1; y++) if (open(rows[y][b.wallCol])) joined = true;
        if (joined) {
          adj[c + ',' + r].push((c + 1) + ',' + r);
          adj[(c + 1) + ',' + r].push(c + ',' + r);
        }
      }
      if (r + 1 < R) {
        let joined = false;
        for (let x = b.x0; x <= b.x1; x++) if (open(rows[b.floor][x])) joined = true;
        if (joined) {
          adj[c + ',' + r].push(c + ',' + (r + 1));
          adj[c + ',' + (r + 1)].push(c + ',' + r);
        }
      }
    }
  }
  return { adj: adj, nodes: nodes };
}
function bfsRooms(adj, from) {
  const d = {}; d[from] = 0;
  const q = [from];
  let h = 0;
  while (h < q.length) {
    const cur = q[h++];
    adj[cur].forEach(function (n) { if (d[n] === undefined) { d[n] = d[cur] + 1; q.push(n); } });
  }
  return d;
}

// ---------------------------------------------------------------------------
// check one level
// ---------------------------------------------------------------------------

function checkOne(level, index) {
  const bad = [];
  function say(m) { bad.push(m); }

  if (!level || !Array.isArray(level.rows) || !level.rows.length) {
    say('has no rows');
    return bad;
  }
  const rows = level.rows;
  const H = rows.length;
  const W = rows[0].length;
  const grid = toGrid(rows);

  const world = Math.floor(index / 6);
  const inWorld = index % 6;
  const wantBoss = inWorld === 5;
  const wantKind = (inWorld === 2 || inWorld === 4) ? 'maze' : 'run';
  const wantH = wantKind === 'run' ? RUN_H : ((inWorld === 4 && world >= 4) ? 51 : 34);

  if (typeof level.name !== 'string' || !level.name.length) say('has no name');
  if (level.world !== world) say('says world ' + level.world + ', slot says ' + world);
  if (level.boss !== wantBoss) say('says boss ' + level.boss + ', slot says ' + wantBoss);
  if (level.kind !== wantKind) say('says kind ' + level.kind + ', slot says ' + wantKind);
  if (H !== wantH) say('has ' + H + ' rows, slot wants ' + wantH);

  rows.forEach(function (row, y) {
    if (typeof row !== 'string') say('row ' + y + ' is not text');
    else if (row.length !== W) say('row ' + y + ' is ' + row.length + ' wide, wanted ' + W);
  });
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (LEGAL.indexOf(rows[y][x]) < 0) say('odd letter "' + rows[y][x] + '" at ' + x + ',' + y);
    }
  }
  if (bad.length) return bad;

  const kind = level.kind;
  const boss = level.boss;

  if (kind === 'run') {
    if (boss) { if (W < 90 || W > 130) say('boss width ' + W + ', wanted 90 to 130'); }
    else if (W < 160 || W > 240) say('run width ' + W + ', wanted 160 to 240');
  } else {
    if (W < 90 || W > 150) say('maze width ' + W + ', wanted 90 to 150');
    if (W % ROOM_W !== 0) say('maze width must divide by ' + ROOM_W);
    if (H % ROOM_H !== 0) say('maze height must divide by ' + ROOM_H);
  }

  const starts = findAll(grid, 'P');
  const flags = findAll(grid, 'F');
  const gems = findAll(grid, 'g');
  if (starts.length !== 1) say('wants one P, found ' + starts.length);
  if (flags.length !== 1) say('wants one F, found ' + flags.length);
  if (gems.length !== 3) say('wants three gems, found ' + gems.length);

  findAll(grid, ALL_ENEMY_CH).forEach(function (e) {
    if (ENEMIES[world].indexOf(e.ch) < 0) say('enemy "' + e.ch + '" is not from world ' + world);
  });
  const bossHere = findAll(grid, ALL_BOSS_CH);
  if (boss) {
    if (bossHere.length !== 1) say('boss level wants one boss, found ' + bossHere.length);
    else if (bossHere[0].ch !== BOSSES[world]) say('wrong boss letter for world ' + world);
  } else if (bossHere.length) say('a normal level must have no boss');

  findAll(grid, ALL_ENEMY_CH + ALL_BOSS_CH).forEach(function (e) {
    const under = e.y + 1 < H ? rows[e.y + 1][e.x] : '.';
    if (SOLID_SET.indexOf(under) < 0) say('"' + e.ch + '" at ' + e.x + ',' + e.y + ' stands on nothing');
  });

  if (LAVA_WORLDS.indexOf(world) < 0 && findAll(grid, '~').length) {
    say('world ' + world + ' must have no lava or deep water');
  }

  findAll(grid, 'T').forEach(function (t) {
    for (let i = 1; i <= 7; i++) {
      const c = t.y - i >= 0 ? rows[t.y - i][t.x] : '#';
      if (SOLID_SET.indexOf(c) >= 0) say('spring at ' + t.x + ',' + t.y + ' is blocked above');
    }
  });

  const stars = findAll(grid, '*');
  if (kind === 'run') {
    if (stars.length !== 1) say('a run level wants one star, found ' + stars.length);
    stars.forEach(function (st) {
      const part = st.x / W;
      if (part < 0.35 || part > 0.55) {
        say('star at ' + st.x + ' is ' + Math.round(part * 100) + ' percent in, wanted 35 to 55');
      }
    });
  } else if (stars.length > 1) say('a maze wants at most one star');

  const weapons = findAll(grid, '123456');
  if (weapons.length < 1 || weapons.length > 2) say('wants 1 or 2 weapons, found ' + weapons.length);
  if (kind === 'run') {
    weapons.forEach(function (wp) {
      if (wp.x > W * 0.68) say('weapon at ' + wp.x + ' is past the first two thirds');
    });
  }

  const coins = findAll(grid, 'o').length;
  const foes = findAll(grid, ALL_ENEMY_CH).length;
  if (kind === 'run' && !boss) {
    if (coins < 30 || coins > 60) say('wants 30 to 60 coins, found ' + coins);
    if (foes < 12 || foes > 22) say('wants 12 to 22 enemies, found ' + foes);
  } else if (kind === 'maze') {
    if (coins < 25 || coins > 50) say('wants 25 to 50 coins, found ' + coins);
    if (foes < 10 || foes > 20) say('wants 10 to 20 enemies, found ' + foes);
  } else {
    if (coins < 10 || coins > 40) say('boss level wants 10 to 40 coins, found ' + coins);
    if (foes < 2 || foes > 8) say('boss level wants 2 to 8 enemies, found ' + foes);
  }

  if (kind === 'run') {
    let run = 0;
    for (let x = 0; x <= W; x++) {
      let hard = false;
      if (x < W) for (let y = 0; y < H; y++) if (SOLID_SET.indexOf(rows[y][x]) >= 0) hard = true;
      if (x < W && !hard) run++;
      else { if (run > 4) say('a hole of ' + run + ' columns ends at ' + x); run = 0; }
    }
    const feats = countFeatures(rows);
    if (W / feats > 4) say('one thing to do only every ' + (W / feats).toFixed(1) + ' columns');
    if (world >= 1 && !boss && !findAll(grid, 'T').length) say('wants at least one spring');
  }

  if (boss && bossHere.length === 1) {
    const b = bossHere[0];
    function plainCol(x) {
      if (x < 1 || x >= W - 1) return false;
      for (let y = 0; y < H; y++) {
        const c = rows[y][x];
        if (y >= RUN_FLOOR) { if (c !== '#') return false; continue; }
        if (c === '.' || c === 'o' || c === b.ch) continue;
        return false;
      }
      return true;
    }
    let left = b.x, right = b.x;
    while (plainCol(left - 1)) left--;
    while (plainCol(right + 1)) right++;
    if (right - left + 1 < 26) say('boss arena is ' + (right - left + 1) + ' columns, wanted 26');
    if (flags.length && flags[0].x < right) say('the flag must be past the arena');
    gems.forEach(function (g) { if (g.x > left) say('gem at ' + g.x + ' is not before the arena'); });
  }

  if (starts.length !== 1 || flags.length !== 1) return bad;

  const solve = analyse(rows);
  if (!solve) { say('no start or no flag'); return bad; }
  if (!solve.ok) say('the solver cannot reach the flag');
  gems.forEach(function (g) {
    if (!solve.ok) return;
    if (!solve.reachable(g.x, g.y)) say('gem at ' + g.x + ',' + g.y + ' cannot be reached');
    else if (!solve.detour(g.x, g.y)) say('gem at ' + g.x + ',' + g.y + ' sits on the main path');
  });

  const traps = solve.traps();
  if (traps.length) {
    say('has ' + traps.length + ' dead end spots, first few: ' + traps.slice(0, 6).join(' '));
  }

  if (kind === 'maze') {
    for (let x = 0; x < W; x++) {
      if (rows[0][x] !== '#') say('top border leaks at ' + x);
      if (rows[H - 1][x] !== '#') say('bottom border leaks at ' + x);
    }
    for (let y = 0; y < H; y++) {
      if (rows[y][0] !== '#') say('left border leaks at ' + y);
      if (rows[y][W - 1] !== '#') say('right border leaks at ' + y);
    }

    const keys = findAll(grid, 'k');
    if (keys.length !== 1) say('a maze wants one key, found ' + keys.length);
    const doorGroups = groupCount(grid, '+');
    if (doorGroups < 1 || doorGroups > 2) say('a maze wants 1 or 2 doors, found ' + doorGroups);
    if (!findAll(grid, '%').length) say('a maze wants a fake wall');

    if (keys.length === 1) {
      const noKey = analyse(rows, { allowKey: false });
      if (!solve.reachable(keys[0].x, keys[0].y)) say('the key cannot be reached');
      if (noKey && !noKey.reachable(keys[0].x, keys[0].y)) say('the key sits behind the door');
      if (noKey && noKey.ok) say('the flag can be reached without the key');
    }

    const C = W / ROOM_W, R = H / ROOM_H;
    const g = roomGraph(rows, C, R);
    const startRoom = roomOf(starts[0].x, starts[0].y);
    const flagRoom = roomOf(flags[0].x, flags[0].y);
    const dist = bfsRooms(g.adj, startRoom);
    g.nodes.forEach(function (n) { if (dist[n] === undefined) say('room ' + n + ' is cut off'); });
    let far = 0;
    g.nodes.forEach(function (n) { if (dist[n] !== undefined && dist[n] > far) far = dist[n]; });
    if (dist[flagRoom] !== far) {
      say('flag room is ' + dist[flagRoom] + ' rooms away, the furthest is ' + far);
    }
    const distFlag = bfsRooms(g.adj, flagRoom);
    const main = {};
    g.nodes.forEach(function (n) {
      if (dist[n] !== undefined && dist[n] + distFlag[n] === dist[flagRoom]) main[n] = true;
    });
    let deep = 0;
    g.nodes.forEach(function (n) {
      if (main[n] || g.adj[n].length !== 1) return;
      let d = 0, cur = n, prev = null;
      while (!main[cur] && d < 60) {
        const nxt = g.adj[cur].filter(function (m) { return m !== prev; })[0];
        if (!nxt) break;
        prev = cur; cur = nxt; d++;
      }
      if (d >= 2) deep++;
    });
    if (deep < 2) say('wants two dead ends two or more rooms deep, found ' + deep);

    const perRoom = {};
    findAll(grid, ALL_ENEMY_CH).forEach(function (e) {
      const k = roomOf(e.x, e.y);
      perRoom[k] = (perRoom[k] || 0) + 1;
    });
    Object.keys(perRoom).forEach(function (k) {
      if (perRoom[k] > 3) say('room ' + k + ' holds ' + perRoom[k] + ' enemies');
    });
  }

  return bad;
}

// ---------------------------------------------------------------------------
// check the whole set
// ---------------------------------------------------------------------------

const globalBad = [];
if (LEVELS.length !== 48) globalBad.push('wants 48 levels, found ' + LEVELS.length);
for (let world = 0; world < 8; world++) {
  let ups = 0;
  for (let i = 0; i < 6; i++) {
    const lv = LEVELS[world * 6 + i];
    if (lv && lv.rows) ups += findAll(toGrid(lv.rows), 'M').length;
  }
  if (ups > 1) globalBad.push('world ' + world + ' has ' + ups + ' max ups, wants at most 1');
}
const seenNames = {};
LEVELS.forEach(function (lv) {
  if (!lv || !lv.name) return;
  if (seenNames[lv.name]) globalBad.push('two levels are both called ' + lv.name);
  seenNames[lv.name] = true;
});

console.log('idx  world         name              kind  size      foes coins gems  result');
console.log('---------------------------------------------------------------------------');

let failed = 0;
const details = [];
LEVELS.forEach(function (lv, i) {
  const bad = checkOne(lv, i);
  const rows = (lv && lv.rows) || [''];
  const grid = toGrid(rows);
  const foes = findAll(grid, ALL_ENEMY_CH).length;
  const coins = findAll(grid, 'o').length;
  const gems = findAll(grid, 'g').length;
  const world = Math.floor(i / 6);
  console.log(
    String(i).padStart(3) + '  ' +
    (WORLD_NAMES[world] || '?').padEnd(13) + ' ' +
    String((lv && lv.name) || '?').padEnd(17) + ' ' +
    String(lv && lv.boss ? 'boss' : (lv && lv.kind) || '?').padEnd(5) + ' ' +
    (rows[0].length + 'x' + rows.length).padEnd(9) + ' ' +
    String(foes).padStart(4) + ' ' +
    String(coins).padStart(5) + ' ' +
    String(gems).padStart(4) + '  ' +
    (bad.length ? 'FAIL' : 'PASS'));
  if (bad.length) {
    failed++;
    details.push({ i: i, name: (lv && lv.name) || '?', bad: bad });
  }
});

console.log('---------------------------------------------------------------------------');
details.forEach(function (d) {
  console.log('level ' + d.i + ' ' + d.name + ':');
  d.bad.forEach(function (m) { console.log('   - ' + m); });
});
globalBad.forEach(function (m) { console.log('whole set: ' + m); });

const total = LEVELS.length;
console.log('');
console.log((total - failed) + '/' + total + ' levels pass');
if (failed || globalBad.length) {
  console.log('CHECK FAILED');
  process.exit(1);
}
console.log('CHECK OK');
